### ISSUE TITLE
`pdm lock` error

### ISSUE THREAD

**Issue by rmekdma** [macro128/pdm-conda#1]
```
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/Users/user/mambaforge/envs/plant/lib/python3.10/site-packages/pdm_conda/plugin.py", line 49, in run_conda
    process.check_returncode()
  File "/Users/user/mambaforge/envs/plant/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['mamba', 'info', '-y', '--json']' returned non-zero exit status 2.
```

`conda info` does not support `-y` option

I guess this line is the problem.
https://github.com/macro128/pdm-conda/blob/3e32dc6c5d9803521608cf4ce83659d28951a480/src/pdm_conda/models/config.py#L165

**Comment by macro128** [comment]
Hi!
Can you show me what command you tried to use so I can reproduce it and add it to the tests?

**Comment by rmekdma** [comment]
@macro128 Thanks for your attention.

This is the code I tried.
- enviroment
    - os: macos 13.2
    - virtual env: [mambaforge](https://github.com/conda-forge/miniforge/#mambaforge) (same as `mamba -c conda-forge`)
    - python: 3.10.9
    - pdm: 2.4.3

```bash
pdm add --conda pytorch -c pytorch
```

**Comment by rmekdma** [comment]
@macro128 I get different result. I didn't install `pdm-conda`.
```
$ mamba search -c pytorch pytorch
Loading channels: ...working... done
# Name                       Version           Build  Channel             
pytorch                        0.4.0 py27_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.0 py35_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.0 py36_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.1 py27_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.1 py35_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.1 py36_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        0.4.1 py37_cuda0.0_cudnn0.0_1  pytorch             
pytorch                        1.0.0         py2.7_1  pytorch             
pytorch                        1.0.0         py3.5_1  pytorch             
pytorch                        1.0.0         py3.6_1  pytorch             
pytorch                        1.0.0         py3.7_1  pytorch             
pytorch                        1.0.1         py2.7_0  pytorch             
pytorch                        1.0.1         py2.7_2  pytorch             
pytorch                        1.0.1         py3.5_0  pytorch             
pytorch                        1.0.1         py3.5_2  pytorch             
pytorch                        1.0.1         py3.6_0  pytorch             
pytorch                        1.0.1         py3.6_2  pytorch             
pytorch                        1.0.1         py3.7_0  pytorch             
pytorch                        1.0.1         py3.7_2  pytorch             
pytorch                        1.1.0         py2.7_0  pytorch             
pytorch                        1.1.0         py3.5_0  pytorch             
pytorch                        1.1.0         py3.6_0  pytorch             
pytorch                        1.1.0         py3.7_0  pytorch             
pytorch                        1.2.0         py2.7_0  pytorch             
pytorch                        1.2.0         py3.5_0  pytorch             
pytorch                        1.2.0         py3.6_0  pytorch             
pytorch                        1.2.0         py3.7_0  pytorch             
pytorch                        1.3.0         py2.7_0  pytorch             
pytorch                        1.3.0         py3.5_0  pytorch             
pytorch                        1.3.0         py3.6_0  pytorch             
pytorch                        1.3.0         py3.7_0  pytorch             
pytorch                        1.3.1         py2.7_0  pytorch             
pytorch                        1.3.1         py3.5_0  pytorch             
pytorch                        1.3.1         py3.6_0  pytorch             
pytorch                        1.3.1         py3.7_0  pytorch             
pytorch                        1.4.0         py2.7_0  pytorch             
pytorch                        1.4.0         py3.5_0  pytorch             
pytorch                        1.4.0         py3.6_0  pytorch             
pytorch                        1.4.0         py3.7_0  pytorch             
pytorch                        1.4.0         py3.8_0  pytorch             
pytorch                        1.5.0         py3.5_0  pytorch             
pytorch                        1.5.0         py3.6_0  pytorch             
pytorch                        1.5.0         py3.7_0  pytorch             
pytorch                        1.5.0         py3.8_0  pytorch             
pytorch                        1.5.1         py3.5_0  pytorch             
pytorch                        1.5.1         py3.6_0  pytorch             
pytorch                        1.5.1         py3.7_0  pytorch             
pytorch                        1.5.1         py3.8_0  pytorch             
pytorch                        1.6.0 cpu_py36hbcfc12f_1  conda-forge         
pytorch                        1.6.0 cpu_py37h20bba8b_1  conda-forge         
pytorch                        1.6.0 cpu_py38h4ef1b2e_1  conda-forge         
pytorch                        1.6.0 cpu_py39hb2aefe7_1  conda-forge         
pytorch                        1.6.0         py3.6_0  pytorch             
pytorch                        1.6.0         py3.7_0  pytorch             
pytorch                        1.6.0         py3.8_0  pytorch             
pytorch                        1.7.0         py3.6_0  pytorch             
pytorch                        1.7.0         py3.7_0  pytorch             
pytorch                        1.7.0         py3.8_0  pytorch             
pytorch                        1.7.1 cpu_py36hbcfc12f_1  conda-forge         
pytorch                        1.7.1 cpu_py36hbcfc12f_2  conda-forge         
pytorch                        1.7.1 cpu_py37h20bba8b_1  conda-forge         
pytorch                        1.7.1 cpu_py37h20bba8b_2  conda-forge         
pytorch                        1.7.1 cpu_py38h4ef1b2e_1  conda-forge         
pytorch                        1.7.1 cpu_py38h4ef1b2e_2  conda-forge         
pytorch                        1.7.1 cpu_py39hb2aefe7_1  conda-forge         
pytorch                        1.7.1 cpu_py39hb2aefe7_2  conda-forge         
pytorch                        1.7.1         py3.6_0  pytorch             
pytorch                        1.7.1         py3.7_0  pytorch             
pytorch                        1.7.1         py3.8_0  pytorch             
pytorch                        1.7.1         py3.9_0  pytorch             
pytorch                        1.8.0 cpu_py36h12aac5e_2  conda-forge         
pytorch                        1.8.0 cpu_py36h12aac5e_3  conda-forge         
pytorch                        1.8.0 cpu_py36h21bc607_1  conda-forge         
pytorch                        1.8.0 cpu_py36h8adebf5_0  conda-forge         
pytorch                        1.8.0 cpu_py37h0262b6d_1  conda-forge         
pytorch                        1.8.0 cpu_py37h6472570_2  conda-forge         
pytorch                        1.8.0 cpu_py37h6472570_3  conda-forge         
pytorch                        1.8.0 cpu_py37hb93c03e_0  conda-forge         
pytorch                        1.8.0 cpu_py38h0797bcf_2  conda-forge         
pytorch                        1.8.0 cpu_py38h0797bcf_3  conda-forge         
pytorch                        1.8.0 cpu_py38h561cec5_1  conda-forge         
pytorch                        1.8.0 cpu_py38h9037c18_0  conda-forge         
pytorch                        1.8.0 cpu_py39h4f2e8f6_0  conda-forge         
pytorch                        1.8.0 cpu_py39h4f2e8f6_1  conda-forge         
pytorch                        1.8.0 cpu_py39hbc4979b_2  conda-forge         
pytorch                        1.8.0 cpu_py39hbc4979b_3  conda-forge         
pytorch                        1.8.0         py3.6_0  pytorch             
pytorch                        1.8.0         py3.7_0  pytorch             
pytorch                        1.8.0         py3.8_0  pytorch             
pytorch                        1.8.0         py3.9_0  pytorch             
pytorch                        1.8.1         py3.6_0  pytorch             
pytorch                        1.8.1         py3.7_0  pytorch             
pytorch                        1.8.1         py3.8_0  pytorch             
pytorch                        1.8.1         py3.9_0  pytorch             
pytorch                        1.9.0 cpu_py36h12aac5e_0  conda-forge         
pytorch                        1.9.0 cpu_py36h2d3ebdf_1  conda-forge         
pytorch                        1.9.0 cpu_py36h41aa04d_2  conda-forge         
pytorch                        1.9.0 cpu_py37h6234483_2  conda-forge         
pytorch                        1.9.0 cpu_py37h6472570_0  conda-forge         
pytorch                        1.9.0 cpu_py37hc5e437f_1  conda-forge         
pytorch                        1.9.0 cpu_py38h0529baa_2  conda-forge         
pytorch                        1.9.0 cpu_py38h490fcb8_1  conda-forge         
pytorch                        1.9.0 cpu_py39h28f9090_2  conda-forge         
pytorch                        1.9.0 cpu_py39h37f9f7c_1  conda-forge         
pytorch                        1.9.0 cpu_py39hbc4979b_0  conda-forge         
pytorch                        1.9.0         py3.6_0  pytorch             
pytorch                        1.9.0         py3.7_0  pytorch             
pytorch                        1.9.0         py3.8_0  pytorch             
pytorch                        1.9.0         py3.9_0  pytorch             
pytorch                        1.9.1 cpu_py36hccde26b_3  conda-forge         
pytorch                        1.9.1 cpu_py37ha02ccf4_3  conda-forge         
pytorch                        1.9.1 cpu_py38h7f09a23_3  conda-forge         
pytorch                        1.9.1 cpu_py39hacab7d8_3  conda-forge         
pytorch                        1.9.1         py3.6_0  pytorch             
pytorch                        1.9.1         py3.7_0  pytorch             
pytorch                        1.9.1         py3.8_0  pytorch             
pytorch                        1.9.1         py3.9_0  pytorch             
pytorch                       1.10.0 cpu_py37ha02ccf4_0  conda-forge         
pytorch                       1.10.0 cpu_py37hf50ba91_1  conda-forge         
pytorch                       1.10.0 cpu_py38h7f09a23_0  conda-forge         
pytorch                       1.10.0 cpu_py38hfbc0695_1  conda-forge         
pytorch                       1.10.0 cpu_py39hacab7d8_0  conda-forge         
pytorch                       1.10.0 cpu_py39he6bcdb8_1  conda-forge         
pytorch                       1.10.0         py3.6_0  pytorch             
pytorch                       1.10.0         py3.7_0  pytorch             
pytorch                       1.10.0         py3.8_0  pytorch             
pytorch                       1.10.0         py3.9_0  pytorch             
pytorch                       1.10.1 cpu_py37h3ff094a_0  conda-forge         
pytorch                       1.10.1 cpu_py38h2cb30f8_0  conda-forge         
pytorch                       1.10.1 cpu_py39h19568cb_0  conda-forge         
pytorch                       1.10.1         py3.6_0  pytorch             
pytorch                       1.10.1         py3.7_0  pytorch             
pytorch                       1.10.1         py3.8_0  pytorch             
pytorch                       1.10.1         py3.9_0  pytorch             
pytorch                       1.10.2 cpu_py37h3ff094a_1  conda-forge         
pytorch                       1.10.2 cpu_py38h2cb30f8_1  conda-forge         
pytorch                       1.10.2 cpu_py39h19568cb_1  conda-forge         
pytorch                       1.10.2         py3.6_0  pytorch             
pytorch                       1.10.2         py3.7_0  pytorch             
pytorch                       1.10.2         py3.8_0  pytorch             
pytorch                       1.10.2         py3.9_0  pytorch             
pytorch                       1.11.0 cpu_py310h345c4ee_0  conda-forge         
pytorch                       1.11.0 cpu_py310h5ac1a50_1  conda-forge         
pytorch                       1.11.0 cpu_py310h5ac1a50_2  conda-forge         
pytorch                       1.11.0 cpu_py37h10adacd_1  conda-forge         
pytorch                       1.11.0 cpu_py37h10adacd_2  conda-forge         
pytorch                       1.11.0 cpu_py37h1fc315f_0  conda-forge         
pytorch                       1.11.0 cpu_py38ha3595c2_1  conda-forge         
pytorch                       1.11.0 cpu_py38ha3595c2_2  conda-forge         
pytorch                       1.11.0 cpu_py38hea469e7_0  conda-forge         
pytorch                       1.11.0 cpu_py39h6185ba3_0  conda-forge         
pytorch                       1.11.0 cpu_py39hfeeed54_1  conda-forge         
pytorch                       1.11.0 cpu_py39hfeeed54_2  conda-forge         
pytorch                       1.11.0        py3.10_0  pytorch             
pytorch                       1.11.0         py3.7_0  pytorch             
pytorch                       1.11.0         py3.8_0  pytorch             
pytorch                       1.11.0         py3.9_0  pytorch             
pytorch                       1.12.0 cpu_py310h32957a8_0  conda-forge         
pytorch                       1.12.0 cpu_py310h32957a8_1  conda-forge         
pytorch                       1.12.0 cpu_py310h32957a8_2  conda-forge         
pytorch                       1.12.0 cpu_py37h8f021e8_0  conda-forge         
pytorch                       1.12.0 cpu_py37h8f021e8_1  conda-forge         
pytorch                       1.12.0 cpu_py37h8f021e8_2  conda-forge         
pytorch                       1.12.0 cpu_py38h03065b0_0  conda-forge         
pytorch                       1.12.0 cpu_py38h03065b0_1  conda-forge         
pytorch                       1.12.0 cpu_py38h03065b0_2  conda-forge         
pytorch                       1.12.0 cpu_py39h9b0ea23_0  conda-forge         
pytorch                       1.12.0 cpu_py39h9b0ea23_1  conda-forge         
pytorch                       1.12.0 cpu_py39h9b0ea23_2  conda-forge         
pytorch                       1.12.0        py3.10_0  pytorch             
pytorch                       1.12.0         py3.7_0  pytorch             
pytorch                       1.12.0         py3.8_0  pytorch             
pytorch                       1.12.0         py3.9_0  pytorch             
pytorch                       1.12.1 cpu_py310h09eaf1a_1  conda-forge         
pytorch                       1.12.1 cpu_py310h248013e_1  conda-forge         
pytorch                       1.12.1 cpu_py310h32957a8_0  conda-forge         
pytorch                       1.12.1 cpu_py37h3bab975_1  conda-forge         
pytorch                       1.12.1 cpu_py37h8f021e8_0  conda-forge         
pytorch                       1.12.1 cpu_py38h03065b0_0  conda-forge         
pytorch                       1.12.1 cpu_py38haabcb56_1  conda-forge         
pytorch                       1.12.1 cpu_py38hc21d861_1  conda-forge         
pytorch                       1.12.1 cpu_py39h0a103a1_1  conda-forge         
pytorch                       1.12.1 cpu_py39h9b0ea23_0  conda-forge         
pytorch                       1.12.1        py3.10_0  pytorch             
pytorch                       1.12.1         py3.7_0  pytorch             
pytorch                       1.12.1         py3.8_0  pytorch             
pytorch                       1.12.1         py3.9_0  pytorch             
pytorch                       1.13.0 cpu_py310h09eaf1a_0  conda-forge         
pytorch                       1.13.0 cpu_py311h4129fe5_0  conda-forge         
pytorch                       1.13.0 cpu_py38hc21d861_0  conda-forge         
pytorch                       1.13.0 cpu_py39h0a103a1_0  conda-forge         
pytorch                       1.13.0        py3.10_0  pytorch             
pytorch                       1.13.0         py3.7_0  pytorch             
pytorch                       1.13.0         py3.8_0  pytorch             
pytorch                       1.13.0         py3.9_0  pytorch             
pytorch                       1.13.1 cpu_py310h09eaf1a_0  conda-forge         
pytorch                       1.13.1 cpu_py310h2bbf33f_1  conda-forge         
pytorch                       1.13.1 cpu_py311h4129fe5_0  conda-forge         
pytorch                       1.13.1 cpu_py311h66d45be_1  conda-forge         
pytorch                       1.13.1 cpu_py38hbb7d42a_1  conda-forge         
pytorch                       1.13.1 cpu_py38hc21d861_0  conda-forge         
pytorch                       1.13.1 cpu_py39h0a103a1_0  conda-forge         
pytorch                       1.13.1 cpu_py39he8d27a1_1  conda-forge         
pytorch                       1.13.1        py3.10_0  pytorch             
pytorch                       1.13.1         py3.7_0  pytorch             
pytorch                       1.13.1         py3.8_0  pytorch             
pytorch                       1.13.1         py3.9_0  pytorch             
```

**Comment by macro128** [comment]
Hi @rmekdma!
Plugin v0.7 and up should work as expected when using mamba/conda runner.

**Comment by rmekdma** [comment]
@macro128 Thanks for the work!
The error message changed. Can you check it out?
I installed pdm-conda 0.7.1 by `pdm add pdm-conda`
It seems that I don't understand how to use pdm/pdm-conda.

### command
```sh
pdm add -v --conda retrying
```

### log
```
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pdm-conda>=0.7.1
pdm.termui:   retrying
pdm.termui:   python>=3.11.3,<3.11.4
pdm.termui:   Adding requirement pdm-conda>=0.7.1
 Lock failed
Unable to find a resolution for pdm-conda
Please make sure the package name is correct.
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/bin/pdm", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/core.py", line 247, in main
    return Core().main(args)
           ^^^^^^^^^^^^^^^^^
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/core.py", line 181, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/core.py", line 176, in main
    f(project, options)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm_conda/cli/commands/add.py", line 87, in handle
    super().handle(project, options)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/cli/commands/add.py", line 57, in handle
    actions.do_add(
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 271, in do_add
    resolved = do_lock(project, strategy, tracked_names, reqs, dry_run=dry_run, hooks=hooks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.11/site-packages/pdm/cli/actions.py", line 115, in do_lock
    raise ResolutionImpossible("Unable to find a resolution") from None
resolvelib.resolvers.ResolutionImpossible: Unable to find a resolution
```

**Comment by macro128** [comment]
Hi @rmekdma, I'm here to help so don't worry.
I suspect some config is missing in pyproject.toml, to check it do this:
1. Install pdm-conda using `pdm self add "pdm-conda>=0.8.0"` (new version with more logs)
2. Run `pdm add -vv --conda retrying`
3. Show me the output and pyproject.toml contents (I just need pdm-conda related part)

If I'm right you might be missing channel and runner info, adding them in pyproject should be enough, for example:
```toml
[tool.pdm.conda]
runner = "mamba"
channels = ["conda-forge"]
```

**Comment by rmekdma** [comment]
I'm sorry. `retrying` is in only pypi. I tried again with `pytorch`
```yaml
[project]
name = "pdm-test"
version = "0"
requires-python = ">=3.8,<3.11"

[tool.pdm.conda]
runner = "mamba"
channels = ["pytorch", "conda-forge"]
dependencies = ["pytorch>=2", "cpuonly"]
```
Error log is quite long, so I upload the file.
[err.txt](https://github.com/macro128/pdm-conda/files/11187331/err.txt)

You can find that pdm tries to install gpu related packages (cudnn, cudatoolkit, libcblas, nccl) even though I add the `cpuonly` dependency.
Maybe this error is from pdm itself?

**Comment by rmekdma** [comment]
Thanks! I think its almost there.
I encountered an Error but this looks easy.

```yaml
[project]
name = "pdm-test"
version = "0"
requires-python = ">=3.8,<3.11"

[tool.pdm.conda]
runner = "mamba"
solver = "libmamba"
channels = ["pytorch", "conda-forge"]
dependencies = ["pytorch>=2", "cpuonly"]
```

```
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/termui.py", line 236, in logging
    yield logger
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/cli/actions.py", line 94, in do_lock
    mapping, dependencies = resolve(
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/resolver/core.py", line 35, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/resolvers.py", line 190, in resolve
    resolution.initialize_conda_resolution(requirements)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/resolvers.py", line 178, in initialize_conda_resolution
    self._p.repository.update_conda_resolution(list(requirements), self._conda_resolution)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/models/repositories.py", line 103, in update_conda_resolution
    resolution = conda_create(
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 317, in conda_create
    name = pkg["name"]
TypeError: 'CondaCandidate' object is not subscriptable
```

**Comment by macro128** [comment]
Hi @rmekdma, it should be fixed with v0.9.1

**Comment by rmekdma** [comment]
Thanks! After I clean the environment I succeeded to `pdm install`.
But when I removed `pdm.lock` and reran `pdm install`, it showed an error.

<details>
<summary>error log</summary>

```
pdm.termui: cmd: conda remove -y --force blas --json
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 97, in run_conda
    process.check_returncode()
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[<CondaRunner.CONDA: 'conda'>, 'remove', '-y', '--force', 'blas', '--json']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 56, in uninstall
    conda_uninstall(self.environment.project, [d.name for d in self._batch_remove], no_deps=True)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 420, in conda_uninstall
    _conda_install(command, packages, dry_run=dry_run, exception_cls=UninstallError)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 363, in _conda_install
    run_conda(command + ["--json"], **kwargs)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 109, in run_conda
    raise exception_cls(msg) from e
pdm.exceptions.RequirementError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 60, in submit
    future.set_result(func(*args, **kwargs))
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 253, in update_candidate
    self.manager.uninstall(dist)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 59, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
pdm.termui: cmd: conda remove -y --force blas mkl --json
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 97, in run_conda
    process.check_returncode()
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[<CondaRunner.CONDA: 'conda'>, 'remove', '-y', '--force', 'blas', 'mkl', '--json']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 56, in uninstall
    conda_uninstall(self.environment.project, [d.name for d in self._batch_remove], no_deps=True)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 420, in conda_uninstall
    _conda_install(command, packages, dry_run=dry_run, exception_cls=UninstallError)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 363, in _conda_install
    run_conda(command + ["--json"], **kwargs)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 109, in run_conda
    raise exception_cls(msg) from e
pdm.exceptions.RequirementError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 60, in submit
    future.set_result(func(*args, **kwargs))
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 253, in update_candidate
    self.manager.uninstall(dist)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 59, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
pdm.termui: cmd: conda remove -y --force blas mkl blas --json
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 97, in run_conda
    process.check_returncode()
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[<CondaRunner.CONDA: 'conda'>, 'remove', '-y', '--force', 'blas', 'mkl', 'blas', '--json']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 56, in uninstall
    conda_uninstall(self.environment.project, [d.name for d in self._batch_remove], no_deps=True)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 420, in conda_uninstall
    _conda_install(command, packages, dry_run=dry_run, exception_cls=UninstallError)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 363, in _conda_install
    run_conda(command + ["--json"], **kwargs)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 109, in run_conda
    raise exception_cls(msg) from e
pdm.exceptions.RequirementError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 60, in submit
    future.set_result(func(*args, **kwargs))
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 253, in update_candidate
    self.manager.uninstall(dist)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 59, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
pdm.termui: cmd: conda remove -y --force blas mkl blas mkl --json
pdm.termui: Error occurs: 
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 97, in run_conda
    process.check_returncode()
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/subprocess.py", line 457, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '[<CondaRunner.CONDA: 'conda'>, 'remove', '-y', '--force', 'blas', 'mkl', 'blas', 'mkl', '--json']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 56, in uninstall
    conda_uninstall(self.environment.project, [d.name for d in self._batch_remove], no_deps=True)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 420, in conda_uninstall
    _conda_install(command, packages, dry_run=dry_run, exception_cls=UninstallError)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 363, in _conda_install
    run_conda(command + ["--json"], **kwargs)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/conda.py", line 109, in run_conda
    raise exception_cls(msg) from e
pdm.exceptions.RequirementError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 60, in submit
    future.set_result(func(*args, **kwargs))
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 253, in update_candidate
    self.manager.uninstall(dist)
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm_conda/installers/manager.py", line 59, in uninstall
    raise UninstallError(e) from e
pdm.exceptions.UninstallError: Error locking dependencies
CondaValueError: You have chosen a non-default solver backend (libmamba) but it was not recognized. Choose one of: classic
pdm.termui: Error occurs
Traceback (most recent call last):
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/termui.py", line 236, in logging
    yield logger
  File "/home1/irteam/home/guswns/apps/mambaforge/envs/pdm/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 397, in synchronize
    raise InstallationError("Some package operations are not complete yet")
pdm.exceptions.InstallationError: Some package operations are not complete yet
```

</details>

**Comment by macro128** [comment]
Seems like the plugin's environment variables were conflicting with conda variables, with v0.9.3 it should be fixed

**Comment by rmekdma** [comment]
Thank you! It's working perfectly. I really appreciate you.
