### ISSUE TITLE
AttributeError: 'PythonEnvironment' object has no attribute 'env_dependencies'

### ISSUE THREAD

**Issue by Firionus** [macro128/pdm-conda#24]
## Steps to reproduce

- Set up pdm with pdm-conda and use the conda interpreter
- Add a global package
- Remove the package

<details>
  <summary>Dockerfile</summary>

```Dockerfile
FROM continuumio/miniconda3:23.9.0-0
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sSL https://pdm-project.org/install-pdm.py | python3 -
ENV PATH="/root/.local/bin:${PATH}"
RUN pdm self add pdm-conda
```
</details>

<details>
  <summary>Console Dump from Docker Container</summary>

```
(base) root@67adafac36ce:/# pdm add -gv cowsay
Changes are written to pyproject.toml.
Adding packages to default dependencies: cowsay
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pip
pdm.termui:   setuptools
pdm.termui:   wheel
pdm.termui:   cowsay
pdm.termui:   python>=3.11.5,<3.11.6
pdm.termui:   Adding requirement pip
pdm.termui:   Adding requirement setuptools
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement cowsay
pdm.termui:   Adding requirement python>=3.11.5,<3.11.6
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11.5,<3.11.6
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin cowsay 6.1
pdm.termui: Pinning: cowsay 6.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin pip 23.3.1
pdm.termui: Pinning: pip 23.3.1
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin setuptools 68.2.2
pdm.termui: Pinning: setuptools 68.2.2
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
STATUS: Resolving: new pin wheel 0.41.3
pdm.termui: Pinning: wheel 0.41.3
pdm.termui: ======== Ending round 4 ========
pdm.termui: ======== Starting round 5 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:       cowsay 6.1
pdm.termui:          pip 23.3.1
pdm.termui:   setuptools 68.2.2
pdm.termui:        wheel 0.41.3
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for cowsay@6.1
pdm.termui: Fetching hashes for wheel@0.41.3
pdm.termui: Fetching hashes for pip@23.3.1
pdm.termui: Fetching hashes for setuptools@68.2.2
🔒 Lock successful
Changes are written to pyproject.toml.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Synchronizing working set with resolved packages: 1 to add, 3 to update, 0 to remove

pdm.termui: Removing distribution pip
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/47/6a/453160888fab7c6a432a6e25f8afe6256d0d9f2cbd25971021da6491d899/pip-23.3.1-py3-none-any.whl (from https://pypi.org/simple/pip/)> (2.1 MB)
  ✔ Update pip 23.2.1 -> 23.3.1 successful
pdm.termui: Removing distribution setuptools
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl (from https://pypi.org/simple/setuptools/)> (807 kB)
Error processing line 1 of /opt/conda/lib/python3.11/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "<frozen site>", line 186, in addpackage
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
  ✔ Update setuptools 68.0.0 -> 68.2.2 successful
pdm.termui: Removing distribution wheel
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/fa/7f/4c07234086edbce4a0a446209dc0cb08a19bb206a3ea53b2f56a403f983b/wheel-0.41.3-py3-none-any.whl (from https://pypi.org/simple/wheel/)> (65 kB)
  ✔ Update wheel 0.41.2 -> 0.41.3 successful
unearth.preparer: Downloading <Link https://files.pythonhosted.org/packages/f1/13/63c0a02c44024ee16f664e0b36eefeb22d54e93531630bd99e237986f534/cowsay-6.1-py3-none-any.whl (from https://pypi.org/simple/cowsay/)> (25 kB)
  ✔ Install cowsay 6.1 successful

🎉 All complete!
(base) root@67adafac36ce:/# pdm remove -gv cowsay
Removing packages from default dependencies: cowsay
Changes are written to pyproject.toml.
STATUS: Resolving dependencies
pdm.termui: ======== Start resolving requirements ========
pdm.termui:   pip
pdm.termui:   setuptools
pdm.termui:   wheel
pdm.termui:   python>=3.11.5,<3.11.6
pdm.termui:   Adding requirement pip
pdm.termui:   Adding requirement setuptools
pdm.termui:   Adding requirement wheel
pdm.termui:   Adding requirement python>=3.11.5,<3.11.6
pdm.termui: ======== Starting round 0 ========
STATUS: Resolving: new pin python>=3.11.5,<3.11.6
pdm.termui: Pinning: python None
pdm.termui: ======== Ending round 0 ========
pdm.termui: ======== Starting round 1 ========
STATUS: Resolving: new pin pip 23.3.1
pdm.termui: Pinning: pip 23.3.1
pdm.termui: ======== Ending round 1 ========
pdm.termui: ======== Starting round 2 ========
STATUS: Resolving: new pin setuptools 68.2.2
pdm.termui: Pinning: setuptools 68.2.2
pdm.termui: ======== Ending round 2 ========
pdm.termui: ======== Starting round 3 ========
STATUS: Resolving: new pin wheel 0.41.3
pdm.termui: Pinning: wheel 0.41.3
pdm.termui: ======== Ending round 3 ========
pdm.termui: ======== Starting round 4 ========
pdm.termui: ======== Resolution Result ========
pdm.termui: Stable pins:
pdm.termui:       python None
pdm.termui:          pip 23.3.1
pdm.termui:   setuptools 68.2.2
pdm.termui:        wheel 0.41.3
STATUS: Fetching hashes for resolved packages...
pdm.termui: Fetching hashes for wheel@0.41.3
pdm.termui: Fetching hashes for pip@23.3.1
pdm.termui: Fetching hashes for setuptools@68.2.2
🔒 Lock successful
Changes are written to pdm.lock.
STATUS: Resolving packages from lockfile...
STATUS: Fetching hashes for resolved packages...
Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm_conda/cli/commands/remove.py", line 45, in handle
    super().handle(project, options)
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/remove.py", line 50, in handle
    self.do_remove(
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/commands/remove.py", line 113, in do_remove
    do_sync(
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/cli/actions.py", line 215, in do_sync
    synchronizer.synchronize()
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 387, in synchronize
    to_add, to_update, to_remove = self.compare_with_working_set()
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm_conda/installers/synchronizers.py", line 53, in compare_with_working_set
    to_remove = [p for p in to_remove if p not in self.environment.env_dependencies]
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pdm/venv/lib/python3.11/site-packages/pdm_conda/installers/synchronizers.py", line 53, in <listcomp>
    to_remove = [p for p in to_remove if p not in self.environment.env_dependencies]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PythonEnvironment' object has no attribute 'env_dependencies'
(base) root@67adafac36ce:/# cowsay -t "I'm still here"
  ______________
| I'm still here |
  ==============
              \
               \
                 ^__^
                 (oo)\_______
                 (__)\       )\/\
                     ||----w |
                     ||     ||

```
</details>

## Actual behavior

- There is an error related to pdm-conda code: `AttributeError: 'PythonEnvironment' object has no attribute 'env_dependencies'
` (see console dump for details)
- The package is not removed

## Expected behavior

- The package should be removed without error

## Environment Information

```
(base) root@67adafac36ce:/# pdm info -g
PDM version:
  2.10.1
Python Interpreter:
  /opt/conda/bin/python (3.11)
Project Root:
  /root/.config/pdm/global-project
Local Packages:

(base) root@67adafac36ce:/# pdm info --env -g
{
  "implementation_name": "cpython",
  "implementation_version": "3.11.5",
  "os_name": "posix",
  "platform_machine": "x86_64",
  "platform_release": "5.15.0-88-generic",
  "platform_system": "Linux",
  "platform_version": "#98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023",
  "python_full_version": "3.11.5",
  "platform_python_implementation": "CPython",
  "python_version": "3.11",
  "sys_platform": "linux"
}
```

**Comment by macro128** [comment]
Hi!
I never tested the plugin behavior when using `--global` flag, if you want to alter some packages from the `base` environment just activate it and run `pdm` inside, if you initialized `pdm-conda` configs on `pyproject.toml` then it should work correctly. If you invoke `pdm add --conda cowsay --runner micromamba --channel conda-forge` or use the following configuration
```toml
[tool.pdm.conda]
runner = "micromamba"
channels = ["conda-forge"]
as-default-manager = true
```
Then `pdm` should modify the active conda environment using `micromamba` correctly.

I might fix `--global` flag compatibility in the future but it's not a priority right now.

**Comment by Firionus** [comment]
Hey :wave: ,

thanks for the response. I think for we can close this. Since [2.10.2](https://github.com/pdm-project/pdm/releases/tag/2.10.2) pdm disallows changing the global conda env.
