### ISSUE TITLE
`unexpected keyword argument 'write'` in `project.add_dependencies()`

### ISSUE THREAD

**Issue by griff-rees** [macro128/pdm-conda#33]
Thanks for the cool project.

Guessing I've done something wrong. Don't see a `Discussion` option for this repo so hope this is the write way to inquire:

```toml
[tool.pdm]
plugins = [
    "pdm-conda"
]

[tool.pdm.conda]
runner = "micromamba"
channels = ["conda-forge/noarch", "conda-forge",]
solver = "libmamba"
```

```python
$ pdm install --plugins
Plugins are installed successfully into .pdm-plugins.
$ pdm add --conda httpx -v
Adding packages to default dependencies: httpx
Traceback (most recent call last):
  File "/Users/grees/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 358, in main
    return core.main(args or sys.argv[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 276, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 271, in main
    self.handle(project, options)
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/core.py", line 207, in handle
    command.handle(project, options)
  File "/Users/grees/code/clim-recal/python/.pdm-plugins/lib/python3.12/site-packages/pdm_conda/cli/commands/add.py", line 123, in handle
    super().handle(project, options)
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 69, in handle
    self.do_add(
  File "/Users/grees/.local/pipx/venvs/pdm/lib/python3.12/site-packages/pdm/cli/commands/add.py", line 159, in do_add
    project.add_dependencies(requirements, group, selection.dev or False, write=False)
TypeError: CondaProject.add_dependencies() got an unexpected keyword argument 'write'
```

**Comment by macro128** [comment]
Hi! It seems to be an issue related to a change on `pdm==2.15.2`, I'll fix it soon, if you want to use the plugin meanwhile you should use `pdm==2.15.1`

**Comment by griff-rees** [comment]
Ah thanks. I'll try when I can. In anticipation: is that likely to have bearing on #34?

**Comment by macro128** [comment]
Nope, this one should be closed after confirming the latest version works ok, for the other I will release another version
